### ISSUE TITLE
articDownloadScheme isn't working with default URL

### ISSUE THREAD

**Issue by ctr26** [connor-lab/ncov2019-artic-nf#71] opened 2020-09-12 15:48 UTC
The default URL leads to a git repo with a submodule which gets missed by a raw git clone, furthermore the code in articDownloadScheme will unintentionally collect from the symlinked sarscov2 folder and the ebola folder found there.

https://github.com/artic-network/artic-ncov2019.git
https://github.com/artic-network/primer-schemes/tree/7d51020f7a4cf96d57d6aeb09bc4413e12ac9787

Best

Craig

**Comment by m-bull** [comment] 2020-09-12 16:46
Hi @ctr26 - the default [URL](https://github.com/connor-lab/ncov2019-artic-nf/blob/e77feedba8ac34c526ed17bb3c111c88f9cb4c7d/conf/base.config#L15) for articDownloadScheme points to https://github.com/artic-network/artic-ncov2019, which I think is the correct place - my tests at least pass using this URL! This was [updated](https://github.com/connor-lab/ncov2019-artic-nf/pull/66/commits/c767b6cab613bf474cbc45debdaf13a69942735c) some four days ago though, so you might need a `git pull` to bring your local repo up to master.

Could you elaborate on the unintentional collection of the ebola scheme?

**Comment by ctr26** [comment] 2020-09-12 16:52
The routine globs for something like /**/V2/*reference.fasta which has 3 hits in the submodu primer-schemes 

https://github.com/artic-network/primer-schemes
 

![received_236467337767896.jpeg](https://user-images.githubusercontent.com/15238739/93000484-ad17d400-f520-11ea-97f0-a81a4af4409e.jpeg)

**Comment by m-bull** [comment] 2020-09-12 16:55
`git pull` should solve - this was fixed in the same commit as above.

**Comment by ctr26** [comment] 2020-09-12 16:58
My bad will try, has the nf-core been updated accordingly?

**Comment by m-bull** [comment] 2020-09-12 17:06
No problem - sorry this is repo is a bit of a moving target. Let me know how it goes with the updated version!

Can you elborate on the nf-core thing? Not quite sure what you mean...

**Comment by ctr26** [comment] 2020-09-12 18:05
As in cloning the repo and running main
.nf

I.e.


`nextflow run connor-lab/ncov2019-artic-nf ....`

Vs


`nextflow run main.nf`

**Comment by yockping** [comment] 2020-12-26 07:46
Hi, facing the similar problem and encounter error when execute the pipeline. Could please advise?
Error as below:

Error executing process > 'ncovIllumina:prepareReferenceFiles:indexReference ([nCoV-2019.reference.fasta, ZaireEbola.reference.fasta, nCoV-2019.reference.fasta])'

Caused by:
  Process `ncovIllumina:prepareReferenceFiles:indexReference` input file name collision -- There are multiple input files for each of the following file names: nCoV-2019.reference.fasta


Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Closed** 2021-09-23 22:16 UTC
